// import FormContainer from "./js/components/container/FormContainer.jsx";
// import FormContainer from "./js/components/container/AddColorFormContainer.jsx";
// import FormContainer from "./js/components/container/StarContainer.jsx";
// import FormContainer from "./js/components/container/ColorsContainer.jsx";
// import FormContainer from "./js/components/presentational/MemberList.jsx";
// import FormContainer from "./js/components/container/ReactChildren.jsx";
// import FormContainer from "./js/components/container/CountryListContainer.jsx";
// import FormContainer from "./js/components/container/HistorySkiingContainer.jsx";
// import FormContainer from "./js/components/container/HOCContainer.jsx";
// import FormContainer from "./js/components/container/ClockContainer.jsx";
// import FormContainer from "./js/components/container/FluxContainer.jsx";
// import FormContainer from "./js/store/ColorStore.jsx";
import FormContainer from "./js/store/StoreFactory.jsx";